config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  get 'index/index'
  post 'new_site', to: 'index#new_site'
  delete 'destroy_site', to: 'index#destroy_site'
  post 'import_sites', to: 'index#import_sites'

  get 'get_sites', to: 'index#get_sites'

  get 'settings', to: 'index#settings'
  post 'update_settings', to: 'index#update_settings'
  post 'update_email', to: 'index#update_email'

  get 'start_monitoring', to: 'index#start_monitoring'
  get 'stop_monitoring', to: 'index#stop_monitoring'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
  validates :url, format: { with: /(https?:\/\/)?([\w\.]+)\.([a-z]{2,6}\.?)(\/[\w\.]*)*\/?/}

  before_create do
    unless (self.url.include? 'http://') || (self.url.include? 'https://')
      self.url = 'http://' + self.url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "admin"
  require "redis"
  @@redis = Redis.new
  @@redis.set('working',0)
  @@redis.set('time_normal',20)
  @@redis.set('time_warning',10)
  Resque.workers.each {|w| w.unregister_worker}

  def index
    @sites = Site.all
    @working = @@redis.get('working')
  end

  def settings
    @time_normal = @@redis.get('time_normal').to_i
    @time_warning = @@redis.get('time_warning').to_i
    @email = @@redis.get('email')
    @working = @@redis.get('working')
  end

  def update_settings
    @@redis.set('time_normal',params[:settings][:time_normal])
    @@redis.set('time_warning',params[:settings][:time_normal])
    redirect_to :back
  end

  def update_email
    @@redis.set('email',params[:update_email][:email])
    redirect_to :back
  end

  def new_site
    @site = Site.create(params.require(:site).permit(:url))
    redirect_to :back
  end

  def destroy_site
    id = params[:id]
    site = Site.find(id)
    site.destroy
    redirect_to :back
  end

  def get_sites
    @sites = Site.all
    render json: {sites: @sites, status: @@redis.get('working')}.to_json
  end

  def import_sites
    uploaded = params[:file]
    if uploaded != nil && File.extname(uploaded.original_filename).downcase == '.txt'
      Site.delete_all
      f = uploaded.open
      f.each do |line|
        site = Site.create(url: line.strip)
      end
    end
    redirect_to :back
  end

  def start_monitoring
    NormalMonitoringJob.set(queue: :normal).perform_later
    WarningMonitoringJob.set(queue: :warning).perform_later
    redirect_to :root
  end

  def stop_monitoring
    @@redis.set('working',0)
    Resque.workers.each {|w| w.unregister_worker}
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/index.html.erb
<% unless @sites.empty? %>
  <h3>Сайты и их статусы</h3>
  <table class="table table-striped">
    <thead>
      <th width="30%">URL</th>
      <th width="60%">Статус</th>
      <th width="10%">Удалить</th>
    </thead>
    <tbody id="sites">
    </tbody>
  </table>
<% end %>

<h3>Добавить URL</h3>
<%= form_for :site, url: new_site_path do |f| %>
    <%= f.text_field :url %>
    <%= f.submit 'Добавить', class: "btn btn-primary" %>
<% end %>

<h3>Загрузить URL из файла</h3>
<i>файл должен быть с расширением .txt </i><br>
<%= form_tag({action: :import_sites}, multipart: true) do %>
  <%= file_field_tag 'file' %><br>
  <%= submit_tag("Загрузить", class: "btn btn-primary" ) %>
<% end %>

<script>
  var getSites = function() {
    $.ajax({
      url: "/get_sites",
      success: function(resp) {
        $("#sites").empty();
        var siteNodes = resp.sites.map(function(site) {
          if (site.status == 'ok') {
            td_class = 'alert alert-success';
          }
          else if (site.status == '302') {
            td_class = 'alert alert-info';
          }
          else {
            td_class = 'alert alert-danger';
          }
          return $("<tr><td>" + site.url + "</td><td class='" + td_class + "'>" + site.status + "</td><td><a class='btn btn-danger' data-method='delete' href='/destroy_site?id=" + site.id + "'>Удалить</a></td></tr>");
        })
        $("#sites").append(siteNodes);
        if (resp.status=="1") {
          status = "работает"
        }
        else {
          status = "остановлен"
        };
        $("#status").empty();
        $("#status").append(status);
      },
      error: function() {
      }
    })
  }

  $(document).on('ready page:load', function(event) {
    getSites();
  });

  setInterval(getSites,5000);
</script>

app/views/index/settings.html.erb
<h3>Управление мониторингом</h3>
<% if @working == '1'%>
  <%= link_to "Запустить сервис", start_monitoring_path, class: "btn btn-primary", :disabled => true %> &nbsp
  <%= link_to "Остановить сервис", stop_monitoring_path, class: "btn btn-danger" %>
<% else %>
  <%= link_to "Запустить сервис", start_monitoring_path, class: "btn btn-primary" %> &nbsp
  <%= link_to "Остановить сервис", stop_monitoring_path, class: "btn btn-danger", :disabled => true %>
<% end %>

<h3>Задержки</h3>
<%= form_for :settings, url: update_settings_path do |f| %>
  <p>
    <%= f.label "Нормальная" %><br>
    <%= f.number_field(:time_normal, in: 10..600, step: 10, value: @time_normal) %>
  </p>
  <p>
    <%= f.label "Аварийная" %><br>
    <%= f.number_field(:time_warning, in: 10..600, step: 10, value: @time_warning) %>
  </p>

  <p>
    <%= f.submit 'Изменить', class: "btn btn-primary" %>
  </p>
<% end %>

<h3>E-mail для уведомлений</h3>
<%= form_for :update_email, url: update_email_path do |f| %>
  <p>
    <%= f.email_field(:email, value: @email) %>
  </p>
  <p>
    <%= f.submit 'Применить', class: "btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatusTester</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 70px;">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">StatusTester</a>
          <ul class="nav navbar-nav">
            <li><%= link_to_unless_current "Сайты", root_path do%></li>
              <li class="active"><a href="#" class="active">Сайты</a></li>
            <% end %>
            <li><%= link_to_unless_current "Настройки", settings_path do%></li>
              <li class="active"><a href="#" class="active">Настройки</a></li>
            <% end %>
          </ul>
          <p class="navbar-text navbar-right">
            Статус сервиса:
            <% if @working == '1'%>
              <b id="status">работает</b>
            <% else %>
              <b id="status">остановлен</b>
            <% end %>
          </p>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>